# This is a configuration file for PyPIC3D
[simulation_parameters]
name = "Demo of a Orszag_TangVortex with 50,000 electrons"
t_wind = 2.5e-8
output_dir = "/home/christopherwoolford/Documents/ResearchCodes/PyPIC3D/demos/ot_vortex"
bc = 'periodic'
solver = 'fdtd'
Nx = 100
Ny = 100
Nz = 1
x_wind = 1
y_wind = 1
z_wind = 1
verbose = false
electrostatic = false
cfl = 0.99
shape_factor = 1

[plotting]
plotting_interval = 10

[field1]
name = "Bx field"
type = 3
path = "Bx.npy"

[field2]
name = "By field"
type = 4
path = "By.npy"

[particle1]
name = "electrons"
N_particles = 30000
weight = 2500000000
charge = -1.602e-19
mass   = 9.1093837e-31
initial_x = 'electron_x.npy'
initial_y = 'electron_y.npy'
initial_z = 'electron_z.npy'
initial_vx = 'electron_vx.npy'
initial_vy = 'electron_vy.npy'
initial_vz = 'electron_vz.npy'


[particle2]
name = "ions"
N_particles = 30000
charge = 1.602e-19
mass = 1.67e-27
weight = 2500000000
initial_x = 'ion_x.npy'
initial_y = 'ion_y.npy'
initial_z = 'ion_z.npy'
initial_vx = 'ion_vx.npy'
initial_vy = 'ion_vy.npy'
initial_vz = 'ion_vz.npy'
update_pos = true
