# This is a configuration file for PyPIC3D
[simulation_parameters]
name = "Test Simulation"
t_wind = 50e-12
output_dir = "/home/christopherwoolford/Documents/PyPIC3D"
bc = 'periodic'
solver = 'spectral'
Nx = 100
Ny = 1
Nz = 1
x_wind = 1e-1
y_wind = 1
z_wind = 1

[plotting]
plot_errors = true
phaseSpace  = false
plotpositions = false
plotKE = false

[particle1]
name = "electrons"
N_particles = 1000
charge = 1.602e-19
mass   = 9.1093837e-31
temperature = 100


[particle2]
name = "ions"
N_particles = 1000
charge = -1.602e-19
mass = 1.67e-27
temperature = 100
