# This is a configuration file for PyPIC3D
[simulation_parameters]
name = "PIC Dev"
t_wind = 300e-12
output_dir = "/home/christopherwoolford/Documents/PyPIC3D"
bc = 'periodic'
solver = 'spectral'
Nx = 200
Ny = 200
Nz = 200
x_wind = 1e-1
y_wind = 1e-1
z_wind = 1e-1
verbose = false
electrostatic = false

[plotting]
plot_errors = true
phaseSpace  = false
plotpositions = true
plotKE = false
plotfields = true
plot_dispersion = false
plotting_interval = 1

[particle1]
name = "electrons"
N_particles = 0
weight = 100
charge = -1.602e-19
mass   = 9.1093837e-31
temperature = 1
xmin = -0.025
xmax =  0.025
ymin = -0.025
ymax =  0.025
zmin = -0.025
zmax =  0.025

[particle2]
name = "ions"
N_particles = 0
weight = 100
charge = 1.602e-19
mass   = 1.67e-27
temperature = 1
xmin = -0.025
xmax =  0.025
ymin = -0.025
ymax =  0.025
zmin = -0.025
zmax =  0.025

[laser1]
max_electric_field = 100000
k0 = 7853981.633974483
omega0 = 2.36e15
pulse_width = 20e-12
xstart = 0.05e-1
ystart = 0
zstart = 0
width  = 1e-1