# This is a configuration file for PyPIC3D
[simulation_parameters]
name = "PIC Dev"
t_wind = 8000e-12
output_dir = "/home/christopherwoolford/Documents/PyPIC3D"
bc = 'periodic'
solver = 'spectral'
Nx = 60
Ny = 30
Nz = 30
x_wind = 1e-2
y_wind = 1e-2
z_wind = 1e-2
verbose = false
electrostatic = true

[plotting]
plot_errors = true
phaseSpace  = false
plotpositions = false
plotKE = false
plotfields = false
plot_dispersion = false
plotting_interval = 100

[particle1]
name = "electrons"
N_particles = 10000
charge = -1.602e-19
mass   = 9.1093837e-31
temperature = 1
update_pos = true
update_v = true

[particle2]
name = "ions"
N_particles = 0
charge = 1.602e-19
mass = 1.67e-27
temperature = 1
update_pos = true
update_v   = true