# This is a configuration file for PyPIC3D
[simulation_parameters]
name = "TS Instability using Spectral methods"
t_wind = 300e-9
output_dir = "/home/christopherwoolford/Documents/PyPIC3D"
bc = 'periodic'
solver = 'spectral'
Nx = 100
Ny = 100
Nz = 100
x_wind = 1e-2
y_wind = 1e-2
z_wind = 1e-2
verbose = true
electrostatic = false

[plotting]
plot_errors = true
phaseSpace  = true
plotpositions = false
plotKE = false
plotfields = true
plot_dispersion = false
plotting_interval = 1

[particle1]
name = "electrons"
N_particles = 1000
charge = -1.602e-19
mass   = 9.1093837e-31
temperature = 1
update_pos = true
update_v = true


[particle2]
name = "ions"
N_particles = 0
charge = 1.602e-19
mass = 1.67e-27
temperature = 1
update_pos = true
update_v   = true