# This is a configuration file for PyPIC3D
[simulation_parameters]
name = "Test Simulation"
t_wind = 30000e-12
output_dir = "/home/christopherwoolford/Documents/PyPIC3D"
bc = 'periodic'
solver = 'spectral'
Nx = 30
Ny = 30
Nz = 30
x_wind = 1e-2
y_wind = 1e-2
z_wind = 1e-2
N_electrons = 5000
N_ions = 5000
Te = 100
Ti = 100
verbose = false
electrostatic = true

[plotting]
plot_errors = false
phaseSpace  = false
plotpositions = false
plotKE = false
plotfields = true
plot_dispersion = true
plotting_interval = 100

[particle1]
name = "electrons"
N_particles = 5000
charge = -1.602e-19
mass   = 9.1093837e-31
temperature = 100
update_pos = true
update_v = true


[particle2]
name = "ions"
N_particles = 5000
charge = 1.602e-19
mass = 1.67e-27
temperature = 100
update_pos = false
update_v   = false