# This is a configuration file for PyPIC3D
[simulation_parameters]
name = "Test Simulation"
t_wind = 1000e-12
output_dir = "/home/christopherwoolford/Documents/PyPIC3D"
bc = 'periodic'
solver = 'spectral'
Nx = 30
Ny = 30
Nz = 30
x_wind = 1e-2
y_wind = 1e-2
z_wind = 1e-2
N_electrons = 100
verbose = true
electrostatic = false

[plotting]
plot_errors = true
phaseSpace  = true
plotpositions = false
plotKE = false
plotfields = false
plotting_interval = 50

[particle1]
name = "electrons"
N_particles = 1000
charge = -1.602e-19
mass   = 9.1093837e-31
temperature = 100
update_pos = true
update_v = true


[particle2]
name = "ions"
N_particles = 1000
charge = 1.602e-19
mass = 1.67e-27
temperature = 100
update_pos = false
update_v   = false