# This is a configuration file for PyPIC3D
[simulation_parameters]
name = "PIC Dev"
t_wind = 8000e-12
output_dir = "/home/christopherwoolford/Documents/PyPIC3D"
bc = 'periodic'
solver = 'spectral'
Nx = 50
Ny = 50
Nz = 50
x_wind = 1e-2
y_wind = 1e-2
z_wind = 1e-2
verbose = false
electrostatic = false

[plotting]
plot_errors = true
phaseSpace  = false
plotpositions = false
plotKE = false
plotfields = true
plot_dispersion = false
plotting_interval = 10

[particle1]
name = "electrons"
N_particles = 0 #0000
weight = 100
charge = -1.602e-19
mass   = 9.1093837e-31
temperature = 1
update_pos = true
update_v = true

[particle2]
name = "ions"
N_particles = 0 #10000
weight = 1000
charge = 1.602e-19
mass = 1.67e-27
temperature = 1
update_pos = true
update_v   = true

#[pec1]
#name = 'PEC wall'
#shape = 'rect'
#xstart = 0.0005
#xstop  = 0.0007
#ystart = 0
#ystop  = 0.001
#zstart = 0
#zstop  = 0.001


