[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "PyPIC3D"
version = "0.1.0"
description = "A 3D Particle-In-Cell simulation package"
authors = [
    { name = "Christopher Woolford", email = "clwoolford@wisc.edu" }
]
license = { file = "LICENSE" }

dependencies = [
    "jax==0.4.38",
    "jaxdecomp==0.2.4",
    "matplotlib==3.10.0",
    "numpy==2.2.2",
    "pandas==2.2.3",
    "plotly==5.24.1",
    "pyevtk==1.6.0",
    "scipy==1.15.1",
    "toml==0.10.2",
    "tqdm==4.66.5",
    "vtk==9.3.1",
    "epyc==1.7.2"
]


[tool.setuptools]
packages = ["PyPIC3D"]
