# This is a configuration file for PyPIC3D
[simulation_parameters]
name = "Demo of a TS instability with 3,000 electrons"
t_wind = 5.413e-8
output_dir = "/home/christopherwoolford/Documents/ResearchCodes/PyPIC3D/demos/two_stream"
bc = 'periodic'
solver = 'fdtd'
Nx = 100
Ny = 1
Nz = 1
x_wind = 1
y_wind = 1
z_wind = 1
verbose = false
electrostatic = false
cfl = 0.9
shape_factor = 2
current_calculation = "j_from_rhov"
alpha = 1.0
relativistic = true

[plotting]
plotting_interval = 8


[particle1]
name = "electron1"
N_particles = 1500
charge = -1.602e-19
mass   = 9.1093837e-31
vth = 14989622.9
ds_per_debye = 6.0
initial_vx = 1e8

[particle2]
name = "electron2"
N_particles = 1500
charge = -1.602e-19
mass   = 9.1093837e-31
vth = 14989622.9
initial_vx = -1e8

[particle3]
name = "ion1"
N_particles = 3000
charge = 1.602e-19
mass = 1.67e-27
vth = 34982.78402326697