# This is a configuration file for PyPIC3D
[simulation_parameters]
name = "Demo of a TS instability with 10,000 electrons"
t_wind = 3000e-12
output_dir = "/home/christopherwoolford/Documents/PyPIC3D"
bc = 'periodic'
solver = 'spectral'
Nx = 100
Ny = 100
Nz = 100
x_wind = 1e-2
y_wind = 1e-2
z_wind = 1e-2
verbose = false
electrostatic = true

[plotting]
plot_errors = true
phaseSpace  = true
plotpositions = false
plotKE = false
plotfields = true
plot_dispersion = false
plotting_interval = 400

[particle1]
name = "electrons"
N_particles = 10000
charge = -1.602e-19
mass   = 9.1093837e-31
temperature = 1
update_pos = true
update_v = true
initial_x = "/home/christopherwoolford/Documents/PyPIC3D/demos/two_stream/x.npy"
initial_y = "/home/christopherwoolford/Documents/PyPIC3D/demos/two_stream/y.npy"
initial_z = "/home/christopherwoolford/Documents/PyPIC3D/demos/two_stream/z.npy"
initial_vx = "/home/christopherwoolford/Documents/PyPIC3D/demos/two_stream/vx.npy"
initial_vy = "/home/christopherwoolford/Documents/PyPIC3D/demos/two_stream/vy.npy"
initial_vz = "/home/christopherwoolford/Documents/PyPIC3D/demos/two_stream/vz.npy"


[particle2]
name = "ions"
N_particles = 0
charge = 1.602e-19
mass = 1.67e-27
temperature = 1
update_pos = true
update_v   = true