# This is a configuration file for PyPIC3D
[simulation_parameters]
name = "Demo of a TS instability with 10,000 electrons"
t_wind = 40e-12
output_dir = "/home/christopherwoolford/Documents/PyPIC3D"
bc = 'periodic'
solver = 'spectral'
Nx = 50
Ny = 50
Nz = 50
x_wind = 1e-3
y_wind = 1e-3
z_wind = 1e-3
verbose = false
electrostatic = false
cfl = 1.0

[plotting]
plot_errors = false
phaseSpace  = true
plotfields = true
plotting_interval = 5

[particle1]
name = "electron1"
N_particles = 10000
charge = -1.602e-19
mass   = 9.1093837e-31
temperature = 1
weight = 1000
initial_vx = 4000
initial_vy = 0
initial_vz = 0
initial_y  = 0
initial_z  = 0
update_y = false
update_z = false

[particle2]
name = "electron2"
N_particles = 10000
charge = -1.602e-19
mass   = 9.1093837e-31
temperature = 1
weight = 1000
initial_vx = -4000
initial_vy = 0
initial_vz = 0
initial_y  = 0
initial_z  = 0
update_y = false
update_z = false