# This is a configuration file for PyPIC3D
[simulation_parameters]
name = "Demo of a TS instability with 10,000 electrons"
t_wind = 2.0e-8
output_dir = "."
bc = 'periodic'
solver = 'spectral'
Nx = 51
Ny = 25
Nz = 25
x_wind = 1e-0
y_wind = 1e-0
z_wind = 1e-0
verbose = false
electrostatic = false
cfl = 1.0

[plotting]
plot_errors = false
phaseSpace  = true
plotfields = true
plotting_interval = 5

[particle1]
name = "electron1"
N_particles = 1500
charge = -1.602e-19
mass   = 9.1093837e-31
temperature = 7412370
weight = 308799888034.3284
initial_vx = 150000000
initial_vy = 0
initial_vz = 0
initial_y  = 0
initial_z  = 0
update_y = false
update_z = false

[particle2]
name = "electron2"
N_particles = 1500
charge = -1.602e-19
mass   = 9.1093837e-31
temperature = 7412370
weight = 308799888034.3284
initial_vx = -150000000
initial_vy = 0
initial_vz = 0
initial_y  = 0
initial_z  = 0
update_y = false
update_z = false