# This is a configuration file for PyPIC3D
[simulation_parameters]
name = "Demo of a TS instability with 10,000 electrons"
t_wind = 1500e-12
output_dir = "/home/christopherwoolford/Documents/PyPIC3D"
bc = 'periodic'
solver = 'spectral'
Nx = 100
Ny = 10
Nz = 10
x_wind = 1e-3
y_wind = 1e-3
z_wind = 1e-3
verbose = false
electrostatic = true

[plotting]
plot_errors = false
phaseSpace  = true
plotpositions = false
plotKE = false
plotfields = false
plot_dispersion = false
plotting_interval = 2000

[particle1]
name = "electrons"
N_particles = 10000
charge = -1.602e-19
mass   = 9.1093837e-31
temperature = 1
update_pos = true
update_v = true
weight = 500
initial_vx = 'demos/two_stream/electron_x_velocities.npy'
initial_vy = 'demos/two_stream/electron_y_velocities.npy'
initial_vz = 'demos/two_stream/electron_z_velocities.npy'
initial_x  = 'demos/two_stream/electron_x_positions.npy'
initial_y  = 'demos/two_stream/electron_y_positions.npy'
initial_z  = 'demos/two_stream/electron_z_positions.npy'