# This is a configuration file for PyPIC3D
# This config loads in a longitudinal E field propagating along x to test the curls.
[simulation_parameters]
name = "Longitudinal E test"
t_wind = 8000e-12
output_dir = "/home/christopherwoolford/Documents/PyPIC3D"
bc = 'periodic'
solver = 'spectral'
Nx = 100
Ny = 50
Nz = 50
x_wind = 1e-2
y_wind = 1e-2
z_wind = 1e-2
verbose = true
electrostatic = false

[plotting]
plot_errors = true
phaseSpace  = false
plotpositions = false
plotKE = false
plotfields = true
plot_dispersion = false
plotting_interval = 1000

[particle1]
name = "electrons"
N_particles = 0 #0000
weight = 100
charge = -1.602e-19
mass   = 9.1093837e-31
temperature = 1
update_pos = true
update_v = true

[field1]
name = 'external_Ex'
type = 0
path = '/home/christopherwoolford/Documents/PyPIC3D/demos/longitudinal/longitudinal_Ex.npy'


[field2]
name = 'external_Ey'
type = 1
path = '/home/christopherwoolford/Documents/PyPIC3D/demos/longitudinal/longitudinal_Ey.npy'


[field3]
name = 'external_Ex'
type = 2
path = '/home/christopherwoolford/Documents/PyPIC3D/demos/longitudinal/longitudinal_Ez.npy'
