# This is a configuration file for PyPIC3D
[simulation_parameters]
name = "Material Demo"
t_wind = 50e-12
output_dir = "/home/christopherwoolford/Documents/PyPIC3D"
bc = 'periodic'
solver = 'spectral'
Nx = 100
Ny = 100
Nz = 100
x_wind = 1e-1
y_wind = 1e-1
z_wind = 1e-1
verbose = false
electrostatic = false

[plotting]
plotvelocities = true
plot_errors = false
phaseSpace  = false
plotpositions = false
plotKE = false
plotfields = true
plot_dispersion = false
plotting_interval = 100

[particle1]
name = "electrons"
N_particles = 10000
weight = 100
charge = -1.602e-19
mass   = 9.1093837e-31
temperature = 293000
bounded = true
fermi_energy = 1.56e-18
xmin = -0.05e-1
xmax = 0.05e-1
ymin = -0.5e-1
ymax = 0.5e-1
zmin = -0.5e-1
zmax = 0.5e-1
w = [76e14, 76e14, 76e14]
g = [10e14, 10e14, 10e14]