# This is a configuration file for PyPIC3D
[simulation_parameters]
name = "Demo of a vxB drift for 1 electron"
t_wind = 2.5e-9
output_dir = "/home/christopherwoolford/Documents/PyPIC3D"
bc = 'periodic'
solver = 'spectral'
Nx = 60
Ny = 30
Nz = 30
x_wind = 1e-2
y_wind = 1e-2
z_wind = 1e-2
verbose = false
electrostatic = true

[plotting]
plot_errors = false
phaseSpace  = false
plotpositions = false
plotKE = false
plotfields = true
plot_dispersion = false
plotting_interval = 100

[particle1]
name = "electrons"
N_particles = 1
charge = -1.602e-19
mass   = 9.1093837e-31
temperature = 1
update_pos = true
update_v = true
initial_x = '/home/christopherwoolford/Documents/PyPIC3D/demos/vxBdrift/x.npy'
initial_y = '/home/christopherwoolford/Documents/PyPIC3D/demos/vxBdrift/y.npy'
initial_z = '/home/christopherwoolford/Documents/PyPIC3D/demos/vxBdrift/z.npy'
initial_vx = '/home/christopherwoolford/Documents/PyPIC3D/demos/vxBdrift/vx.npy'
initial_vy = '/home/christopherwoolford/Documents/PyPIC3D/demos/vxBdrift/vy.npy'
initial_vz = '/home/christopherwoolford/Documents/PyPIC3D/demos/vxBdrift/vz.npy'

[field1]
name = 'external_By'
type = 4
path = '/home/christopherwoolford/Documents/PyPIC3D/demos/vxBdrift/By.npy'