# This is a configuration file for PyPIC3D
[simulation_parameters]
name = "Demo of a 1D Weibel instability with 3,000 electrons"
Nt = 6000
bc = 'periodic'
solver = 'fdtd'
Nx = 201
Ny = 1
Nz = 1
x_wind = 3e-1
y_wind = 1
z_wind = 1
verbose = false
electrostatic = false
cfl = 0.5
shape_factor = 1
relativistic = true

[plotting]
plot_errors = false
phaseSpace  = false
plotfields = false
plotting_interval = 30

[particle1]
name = "electron1"
N_per_cell =    40
charge = -1.602e-19
mass   = 9.1093837e-31
ds_per_debye = 0.7
Tx     = 296494.82871735515
Tz     = 29649482.87173552
Ty     = 0

[particle2]
name = "ion1"
N_per_cell =    40
charge = 1.602e-19
mass = 1.67e-27
Tx     = 296494.82871735515
Tz     = 29649482.87173552
Ty     = 0