# This is a configuration file for PyPIC3D
[simulation_parameters]
name = "Demo of a Weibel instability with 20,000 electrons"
t_wind = 50e-9
output_dir = "/home/christopherwoolford/Documents/ResearchCodes/PyPIC3D/demos/weibel"
bc = 'periodic'
solver = 'fdtd'
Nx = 50
Ny = 50
Nz = 1
x_wind = 1
y_wind = 1
z_wind = 1
verbose = false
electrostatic = false
cfl = 0.99
shape_factor = 2

[plotting]
plot_errors = false
phaseSpace  = false
plotfields = false
plotting_interval = 30

[particle1]
name = "electron1"
N_particles = 20000
charge = -1.602e-19
mass   = 9.1093837e-31
Tx      = 1185374.44057971
Ty      = 11853.7444057971
Tz      = 0.0
ds_per_debye = 6.0
initial_vx = 'electron1_vx.npy'
initial_z  = 'electron1_z.npy'

[particle2]
name = "ion1"
N_particles = 20000
charge = 1.602e-19
mass = 1.67e-27
T     = 0.0
initial_x = 'ion_x.npy'
initial_y = 'ion_y.npy'
initial_z = 'ion_z.npy'
update_pos = false