# This is a configuration file for PyPIC3D
[simulation_parameters]
name = "Test of the periodic boundary conditions"
t_wind = 2.5e-9
output_dir = "/home/christopherwoolford/Documents/PyPIC3D"
GPUs = false
solver = 'spectral'
Nx = 30
Ny = 30
Nz = 30
x_wind = 1e-1
y_wind = 1e-1
z_wind = 1e-1
verbose = false
electrostatic = true

[plotting]
plot_errors = false
phaseSpace  = false
plotpositions = false
plotKE = false
plotfields = true
plot_dispersion = false
plotting_interval = 50

[particle1]
name = "electrons"
N_particles = 1
bc = 'reflecting'
charge = -1.602e-19
mass   = 9.1093837e-31
temperature = 1
update_x = true
initial_x = '/home/christopherwoolford/Documents/PyPIC3D/demos/periodic_bc/x.npy'
initial_y = '/home/christopherwoolford/Documents/PyPIC3D/demos/periodic_bc/y.npy'
initial_z = '/home/christopherwoolford/Documents/PyPIC3D/demos/periodic_bc/z.npy'
initial_vx = '/home/christopherwoolford/Documents/PyPIC3D/demos/periodic_bc/vx.npy'
initial_vy = '/home/christopherwoolford/Documents/PyPIC3D/demos/periodic_bc/vy.npy'
initial_vz = '/home/christopherwoolford/Documents/PyPIC3D/demos/periodic_bc/vz.npy'