# This is a PyPIC3D configuration file

# This is a simulation of the pierce diode instability
# The pierce diode instability is instability triggered by
# a current between parallel plate PECs that causes the formation
# of a virtual cathode.


[simulation_parameters]
name = "Demo of a pierce diode instability with 3,000 electrons"
t_wind = 1.67e-8
solver = 'electrostatic'
Nx = 200
Ny = 1
Nz = 1
particle_tile_nx = 200
particle_tile_ny = 1
particle_tile_nz = 1
particle_tile_capacity_factor=1.0
x_wind = 0.1
y_wind = 1
z_wind = 1
verbose = false
cfl = 0.99
shape_factor = 2
alpha = 1.0
relativistic = true
particle_x_bc = "reflecting"
particle_y_bc = "periodic"
particle_z_bc = "periodic"
x_bc = "conducting"
y_bc = "periodic"
z_bc = "periodic"


[plotting]
plotting_interval = 1
plot_openpmd_particles = true
plot_openpmd_fields = true

# electron beam current
[particle1]
name = "electron1"
N_particles = 10000
charge = -1.602e-19
mass   = 9.1093837e-31
vth = 0
weight =  1.61e+10
initial_vx = 6.00e7

# static ions for neutralizing background
[particle2]
name = "ion1"
N_particles = 10000
charge = 1.602e-19
mass = 1.67e-27
vth = 0.0
update_x = false
update_y = false
update_z = false