# This is a configuration file for PyPIC3D
[simulation_parameters]
name = "Demo of Plasma Oscillations with 10,000 electrons"
t_wind = 1000e-12
output_dir = "/home/christopherwoolford/Documents/PyPIC3D"
bc = 'periodic'
solver = 'spectral'
Nx = 100
Ny = 100
Nz = 100
x_wind = 1e-2
y_wind = 1e-2
z_wind = 1e-2
verbose = false
electrostatic = false
initial_B = true

[plotting]
plot_errors = false
phaseSpace  = true
plotpositions = false
plotKE = true
plotfields = true
plot_dispersion = false
plotting_interval = 1

[particle1]
name = "electrons"
N_particles = 50000
charge = -1.602e-19
mass   = 9.1093837e-31
temperature = 1
weight = 1000
initial_x = 'demos/plasma_oscillations/x.npy'
initial_y = 'demos/plasma_oscillations/y.npy'
initial_z = 'demos/plasma_oscillations/z.npy'


[particle2]
name = "ions"
N_particles = 50000
charge = 1.602e-19
mass   = 1.67e-27
temperature = 1
weight = 1000